export const designTokens = {
  colors: {
    background: "#1E2229",
    backgroundSecondary: "#242933",
    panel: "#2B313C",
    panelHover: "#343B48",
    border: "#48515F",
    borderStrong: "#5C6675",
    accent: "#A3ACB8",
    accentSoft: "#B8C0CA",
    bullish: "#95B8A3",
    bearish: "#BD9292",
    warning: "#C9B17D",
    highlight: "#F1E7D4",
    textPrimary: "#F4EFE7",
    textSecondary: "#D3CCC2",
    mutedText: "#AAB3BF",
    success: "#95B8A3",
    danger: "#BD9292",
    positiveTagBg: "rgba(149,184,163,0.14)",
    negativeTagBg: "rgba(189,146,146,0.14)",
    panelInset: "#232832",
  },
  typography: {
    fontFamily: '"IBM Plex Sans", "Noto Sans TC", Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    monoFamily: '"IBM Plex Mono", "SFMono-Regular", Consolas, "Liberation Mono", monospace',
    pageTitle: "34px",
    sectionTitle: "22px",
    panelTitle: "16px",
    body: "14px",
    micro: "11px",
  },
  radii: {
    panel: "12px",
    control: "10px",
    compact: "8px",
  },
  spacing: {
    railWidth: "64px",
    railGap: "24px",
    pagePadding: "20px",
    panelPadding: "16px",
  },
  icons: {
    size: 18,
    default: "#A3ACB8",
    hover: "#F1E7D4",
    active: "#F4EFE7",
    activeBackground: "#343B48",
  },
  panel: {
    className: "terminal-panel rounded-xl border border-[var(--theme-border)] bg-[var(--theme-panel)]",
    hoverClassName: "transition-colors hover:bg-[var(--theme-panel-hover)]",
  },
} as const;

export type DesignTokens = typeof designTokens;
