from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List


@dataclass(frozen=True)
class ThemeDefinition:
    name: str
    category: str
    description: str
    etf_symbols: tuple[str, ...]
    tickers: tuple[str, ...]
    supply_chain: Dict[str, tuple[str, ...]]
    narrative_keywords: tuple[str, ...]
    macro_alignment: tuple[str, ...]


THEME_UNIVERSE: tuple[ThemeDefinition, ...] = (
    ThemeDefinition(
        "AI Infrastructure",
        "Technology",
        "Compute, networking, power and cooling infrastructure required for AI data centers.",
        ("SMH", "XLK"),
        ("NVDA", "AMD", "AVGO", "ANET", "VRT", "ETN", "DELL", "SMCI"),
        {
            "upstream": ("TSM", "ASML", "AMAT", "LRCX"),
            "materials": ("MU", "GLW"),
            "equipment": ("ANET", "AVGO", "VRT", "ETN"),
            "manufacturers": ("NVDA", "AMD", "DELL", "SMCI"),
            "infrastructure": ("PWR", "TT", "CARR"),
            "downstream_integrators": ("MSFT", "AMZN", "GOOGL", "META"),
        },
        ("AI capex", "data center", "GPU", "accelerator", "inference", "training"),
        ("risk_on", "liquidity", "AI_capex"),
    ),
    ThemeDefinition(
        "Semiconductor",
        "Technology",
        "Semiconductor leaders, foundry capacity, analog, equipment and design infrastructure.",
        ("SMH", "SOXX"),
        ("NVDA", "AMD", "AVGO", "QCOM", "AMAT", "LRCX", "KLAC", "TSM"),
        {
            "upstream": ("ASML", "AMAT", "LRCX", "KLAC"),
            "materials": ("MU", "WDC", "GLW"),
            "equipment": ("ASML", "AMAT", "LRCX", "KLAC"),
            "manufacturers": ("NVDA", "AMD", "AVGO", "QCOM", "TSM"),
            "infrastructure": ("ANET", "MRVL"),
            "downstream_integrators": ("AAPL", "MSFT", "AMZN"),
        },
        ("semiconductor", "chip", "foundry", "wafer", "equipment"),
        ("risk_on", "AI_capex"),
    ),
    ThemeDefinition(
        "HBM",
        "Memory",
        "High bandwidth memory cycle connected to AI accelerators and advanced packaging.",
        ("SMH",),
        ("MU", "NVDA", "AMD", "TSM", "AMAT", "LRCX"),
        {
            "upstream": ("AMAT", "LRCX", "KLAC"),
            "materials": ("MU", "WDC"),
            "equipment": ("AMAT", "LRCX"),
            "manufacturers": ("MU", "TSM"),
            "infrastructure": ("NVDA", "AMD"),
            "downstream_integrators": ("MSFT", "AMZN", "META"),
        },
        ("HBM", "memory bandwidth", "AI memory", "advanced packaging"),
        ("AI_capex",),
    ),
    ThemeDefinition(
        "DRAM Cycle",
        "Memory",
        "DRAM pricing, inventory normalization and memory capital spending cycle.",
        ("SMH",),
        ("MU", "WDC", "STX", "AMAT", "LRCX"),
        {
            "upstream": ("AMAT", "LRCX"),
            "materials": ("MU", "WDC"),
            "equipment": ("AMAT", "LRCX"),
            "manufacturers": ("MU", "WDC", "STX"),
            "infrastructure": ("DELL", "HPQ"),
            "downstream_integrators": ("NVDA", "AMD"),
        },
        ("DRAM", "memory pricing", "inventory correction", "memory cycle"),
        ("risk_on",),
    ),
    ThemeDefinition(
        "NAND Cycle",
        "Memory",
        "NAND flash pricing, storage demand and device replacement cycle.",
        ("SMH",),
        ("MU", "WDC", "STX", "HPQ", "DELL"),
        {
            "upstream": ("AMAT", "LRCX"),
            "materials": ("MU", "WDC"),
            "equipment": ("AMAT", "LRCX"),
            "manufacturers": ("MU", "WDC", "STX"),
            "infrastructure": ("DELL", "HPQ"),
            "downstream_integrators": ("AAPL", "AMZN"),
        },
        ("NAND", "flash", "storage", "SSD", "memory pricing"),
        ("risk_on",),
    ),
    ThemeDefinition(
        "Glass Substrate",
        "Semiconductor Supply Chain",
        "Advanced substrate and materials capacity for next-generation chip packaging.",
        ("SMH",),
        ("GLW", "AMAT", "INTC", "TSM", "KLAC"),
        {
            "upstream": ("GLW",),
            "materials": ("GLW",),
            "equipment": ("AMAT", "KLAC"),
            "manufacturers": ("INTC", "TSM"),
            "infrastructure": ("ASML",),
            "downstream_integrators": ("NVDA", "AMD"),
        },
        ("glass substrate", "advanced substrate", "packaging", "interposer"),
        ("AI_capex",),
    ),
    ThemeDefinition(
        "CoWoS",
        "Semiconductor Supply Chain",
        "Advanced packaging capacity and bottlenecks for AI accelerator supply chains.",
        ("SMH",),
        ("TSM", "AMAT", "KLAC", "ASML", "NVDA", "AMD"),
        {
            "upstream": ("ASML", "AMAT", "KLAC"),
            "materials": ("MU", "GLW"),
            "equipment": ("AMAT", "KLAC"),
            "manufacturers": ("TSM", "NVDA", "AMD"),
            "infrastructure": ("AVGO", "ANET"),
            "downstream_integrators": ("MSFT", "AMZN", "META"),
        },
        ("CoWoS", "advanced packaging", "packaging capacity", "TSMC capacity"),
        ("AI_capex",),
    ),
    ThemeDefinition(
        "Networking",
        "Technology Infrastructure",
        "Ethernet, switching, optical and data center networking buildout.",
        ("XLK",),
        ("ANET", "CSCO", "AVGO", "MRVL", "CIEN", "JNPR"),
        {
            "upstream": ("AVGO", "MRVL"),
            "materials": ("GLW", "APH"),
            "equipment": ("ANET", "CSCO", "CIEN"),
            "manufacturers": ("ANET", "CSCO", "JNPR"),
            "infrastructure": ("VRT", "ETN"),
            "downstream_integrators": ("MSFT", "AMZN", "GOOGL", "META"),
        },
        ("ethernet", "switching", "optical", "networking", "AI cluster"),
        ("AI_capex", "risk_on"),
    ),
    ThemeDefinition(
        "Data Center Cooling",
        "Infrastructure",
        "Thermal management, liquid cooling and mechanical systems for high-density compute.",
        ("XLI",),
        ("VRT", "TT", "ETN", "JCI", "CARR", "PWR"),
        {
            "upstream": ("ETN", "PWR"),
            "materials": ("APH",),
            "equipment": ("VRT", "TT", "JCI", "CARR"),
            "manufacturers": ("VRT", "TT"),
            "infrastructure": ("PWR", "ETN"),
            "downstream_integrators": ("MSFT", "AMZN", "GOOGL"),
        },
        ("liquid cooling", "thermal", "data center cooling", "power density"),
        ("AI_capex",),
    ),
    ThemeDefinition(
        "Electric Grid",
        "Infrastructure",
        "Power grid modernization, electrification, transformers and utility capex.",
        ("XLU", "XLI"),
        ("ETN", "PWR", "HUBB", "NEE", "SO", "DUK", "AEP"),
        {
            "upstream": ("FCX", "SCCO"),
            "materials": ("FCX", "SCCO", "TECK"),
            "equipment": ("ETN", "HUBB"),
            "manufacturers": ("ETN", "PWR", "HUBB"),
            "infrastructure": ("NEE", "SO", "DUK", "AEP"),
            "downstream_integrators": ("MSFT", "AMZN", "GOOGL"),
        },
        ("grid", "transformer", "power demand", "electrification", "utility capex"),
        ("AI_capex", "inflation"),
    ),
    ThemeDefinition(
        "Cable / Copper",
        "Materials",
        "Copper, cable, connector and electrical component demand from grid and data centers.",
        ("XLB", "XLI"),
        ("FCX", "SCCO", "TECK", "APH", "TEL", "GLW"),
        {
            "upstream": ("FCX", "SCCO", "TECK"),
            "materials": ("FCX", "SCCO", "TECK"),
            "equipment": ("APH", "TEL", "GLW"),
            "manufacturers": ("APH", "TEL"),
            "infrastructure": ("ETN", "PWR"),
            "downstream_integrators": ("NEE", "SO", "DUK"),
        },
        ("copper", "cable", "connector", "electrification", "grid buildout"),
        ("inflation", "AI_capex"),
    ),
    ThemeDefinition(
        "Nuclear Energy",
        "Energy",
        "Nuclear generation, uranium and long-duration power demand from AI/data centers.",
        ("XLU", "XLE"),
        ("CEG", "VST", "NEE", "SMR", "CCJ", "BWXT"),
        {
            "upstream": ("CCJ",),
            "materials": ("CCJ",),
            "equipment": ("BWXT", "SMR"),
            "manufacturers": ("CEG", "VST", "NEE"),
            "infrastructure": ("CEG", "VST"),
            "downstream_integrators": ("MSFT", "AMZN", "GOOGL"),
        },
        ("nuclear", "uranium", "small modular reactor", "baseload", "data center power"),
        ("AI_capex", "risk_off"),
    ),
    ThemeDefinition(
        "Utilities",
        "Defensive",
        "Regulated utilities, load growth and defensive income under changing rate regimes.",
        ("XLU",),
        ("NEE", "SO", "DUK", "AEP", "SRE", "EXC"),
        {
            "upstream": ("ETN", "PWR"),
            "materials": ("FCX",),
            "equipment": ("HUBB", "ETN"),
            "manufacturers": ("NEE", "SO", "DUK"),
            "infrastructure": ("AEP", "SRE", "EXC"),
            "downstream_integrators": ("AMZN", "MSFT"),
        },
        ("utility", "rate base", "load growth", "regulated utility"),
        ("risk_off", "rates_down"),
    ),
    ThemeDefinition(
        "Shipping",
        "Global Trade",
        "Ocean shipping, freight rates, port congestion and global trade acceleration.",
        ("IYT",),
        ("ZIM", "DAC", "SBLK", "GNK", "MATX", "KEX"),
        {
            "upstream": ("XOM", "CVX"),
            "materials": ("NUE", "STLD"),
            "equipment": ("KEX", "MATX"),
            "manufacturers": ("ZIM", "DAC", "SBLK", "GNK"),
            "infrastructure": ("KEX", "MATX"),
            "downstream_integrators": ("FDX", "UPS", "XPO"),
        },
        ("freight", "Baltic Dry", "port congestion", "shipping rates", "container"),
        ("global_trade", "oil"),
    ),
    ThemeDefinition(
        "Commodities",
        "Materials",
        "Broad commodity producers across energy, metals and precious metals.",
        ("XLB", "DBC"),
        ("FCX", "XOM", "CVX", "NEM", "SCCO", "TECK"),
        {
            "upstream": ("XOM", "CVX", "FCX", "SCCO"),
            "materials": ("FCX", "SCCO", "NEM", "TECK"),
            "equipment": ("CAT", "DE"),
            "manufacturers": ("XOM", "CVX", "NEM"),
            "infrastructure": ("PWR", "ETN"),
            "downstream_integrators": ("VMC", "MLM"),
        },
        ("commodity", "metals", "gold", "oil", "mining"),
        ("inflation", "oil"),
    ),
    ThemeDefinition(
        "Infrastructure",
        "Industrials",
        "Civil infrastructure, grid buildout, machinery and construction equipment.",
        ("XLI", "PAVE"),
        ("PWR", "CAT", "URI", "VMC", "MLM", "DE"),
        {
            "upstream": ("NUE", "STLD", "FCX"),
            "materials": ("VMC", "MLM", "NUE"),
            "equipment": ("CAT", "DE", "URI"),
            "manufacturers": ("PWR", "CAT", "DE"),
            "infrastructure": ("PWR", "VMC", "MLM"),
            "downstream_integrators": ("DHI", "LEN", "PHM"),
        },
        ("infrastructure", "construction spending", "capex", "public works"),
        ("fiscal", "rates_down"),
    ),
    ThemeDefinition(
        "Industrial Automation",
        "Industrials",
        "Factory automation, process control, electrification and industrial productivity.",
        ("XLI",),
        ("ROK", "EMR", "HON", "ETN", "ITW", "PH"),
        {
            "upstream": ("APH", "TEL"),
            "materials": ("NUE", "FCX"),
            "equipment": ("ROK", "EMR", "HON"),
            "manufacturers": ("ETN", "ITW", "PH"),
            "infrastructure": ("PWR",),
            "downstream_integrators": ("CAT", "DE"),
        },
        ("automation", "factory", "industrial productivity", "electrification"),
        ("risk_on", "capex"),
    ),
    ThemeDefinition(
        "Robotics",
        "Automation",
        "Robotics, surgical automation, warehouse automation and AI-enabled machinery.",
        ("BOTZ", "ROBO"),
        ("ISRG", "TER", "ROK", "AMZN", "NVDA", "SYM"),
        {
            "upstream": ("NVDA", "TER"),
            "materials": ("APH", "TEL"),
            "equipment": ("ROK", "TER"),
            "manufacturers": ("ISRG", "SYM", "AMZN"),
            "infrastructure": ("MSFT", "AMZN"),
            "downstream_integrators": ("WMT", "TGT"),
        },
        ("robotics", "automation", "warehouse automation", "surgical robot"),
        ("risk_on", "AI_capex"),
    ),
    ThemeDefinition(
        "Defense",
        "Aerospace & Defense",
        "Defense primes, missile systems, aerospace platforms and national security budgets.",
        ("ITA", "XAR"),
        ("LMT", "RTX", "NOC", "GD", "LHX", "BA"),
        {
            "upstream": ("NUE", "ATI"),
            "materials": ("NUE", "ATI"),
            "equipment": ("RTX", "LHX"),
            "manufacturers": ("LMT", "NOC", "GD", "BA"),
            "infrastructure": ("RTX", "LHX"),
            "downstream_integrators": ("LMT", "NOC", "GD"),
        },
        ("defense", "missile", "aerospace", "security", "military"),
        ("risk_off", "fiscal"),
    ),
    ThemeDefinition(
        "Financials",
        "Financial Services",
        "Banks, capital markets, payments and credit cycle beneficiaries.",
        ("XLF",),
        ("JPM", "BAC", "GS", "MS", "V", "MA", "AXP"),
        {
            "upstream": ("ICE", "CME"),
            "materials": tuple(),
            "equipment": ("V", "MA"),
            "manufacturers": ("JPM", "BAC", "GS", "MS"),
            "infrastructure": ("ICE", "CME"),
            "downstream_integrators": ("AXP", "V", "MA"),
        },
        ("bank", "credit", "capital markets", "payments", "yield curve"),
        ("rates", "risk_on"),
    ),
    ThemeDefinition(
        "Healthcare",
        "Healthcare",
        "Pharma, managed care, medical devices and defensive healthcare leadership.",
        ("XLV",),
        ("LLY", "UNH", "JNJ", "MRK", "ABBV", "PFE", "ISRG"),
        {
            "upstream": ("TMO", "DHR"),
            "materials": ("TMO", "DHR"),
            "equipment": ("ISRG", "ABT"),
            "manufacturers": ("LLY", "MRK", "ABBV", "PFE"),
            "infrastructure": ("UNH", "CI"),
            "downstream_integrators": ("CVS", "UNH"),
        },
        ("healthcare", "GLP-1", "drug approval", "medical device", "managed care"),
        ("risk_off", "defensive"),
    ),
    ThemeDefinition(
        "Renewable Energy",
        "Energy Transition",
        "Solar, renewable developers, storage and energy transition infrastructure.",
        ("ICLN", "TAN"),
        ("FSLR", "ENPH", "NEE", "SEDG", "BEP", "RUN"),
        {
            "upstream": ("FSLR", "ENPH"),
            "materials": ("ALB", "FCX"),
            "equipment": ("ENPH", "SEDG"),
            "manufacturers": ("FSLR", "NEE", "BEP"),
            "infrastructure": ("NEE", "RUN"),
            "downstream_integrators": ("TSLA", "GM"),
        },
        ("renewable", "solar", "storage", "energy transition", "clean energy"),
        ("rates_down", "fiscal"),
    ),
    ThemeDefinition(
        "Traditional Industries",
        "Industrials",
        "Old economy industrials, machinery, chemicals and real-asset rotation.",
        ("XLI", "XLB"),
        ("CAT", "DE", "EMR", "ITW", "DOW", "DD"),
        {
            "upstream": ("FCX", "NUE"),
            "materials": ("DOW", "DD", "NUE"),
            "equipment": ("CAT", "DE"),
            "manufacturers": ("EMR", "ITW"),
            "infrastructure": ("PWR", "VMC"),
            "downstream_integrators": ("URI", "DHI"),
        },
        ("old economy", "industrial", "machinery", "chemicals", "real assets"),
        ("inflation", "fiscal"),
    ),
    ThemeDefinition(
        "Construction",
        "Housing & Construction",
        "Homebuilders, aggregates, rental equipment and construction activity.",
        ("XHB", "ITB"),
        ("DHI", "LEN", "PHM", "VMC", "MLM", "URI"),
        {
            "upstream": ("NUE", "STLD"),
            "materials": ("VMC", "MLM"),
            "equipment": ("URI", "CAT"),
            "manufacturers": ("DHI", "LEN", "PHM"),
            "infrastructure": ("VMC", "MLM"),
            "downstream_integrators": ("HD", "LOW"),
        },
        ("construction", "homebuilding", "housing", "aggregates", "building permits"),
        ("rates_down", "fiscal"),
    ),
    ThemeDefinition(
        "Steel",
        "Materials",
        "Steel producers, mini mills and industrial material demand.",
        ("SLX", "XME"),
        ("NUE", "STLD", "X", "CLF", "RS"),
        {
            "upstream": ("CLF",),
            "materials": ("NUE", "STLD", "X", "CLF"),
            "equipment": ("CAT",),
            "manufacturers": ("NUE", "STLD", "RS"),
            "infrastructure": ("VMC", "PWR"),
            "downstream_integrators": ("CAT", "DE", "DHI"),
        },
        ("steel", "mini mill", "hot rolled coil", "industrial metals"),
        ("inflation", "fiscal"),
    ),
    ThemeDefinition(
        "Cement",
        "Materials",
        "Aggregates, cement and heavy construction material demand.",
        ("XLB", "PAVE"),
        ("VMC", "MLM", "CRH", "EXP"),
        {
            "upstream": ("NUE", "FCX"),
            "materials": ("VMC", "MLM", "CRH", "EXP"),
            "equipment": ("CAT", "URI"),
            "manufacturers": ("VMC", "MLM", "CRH"),
            "infrastructure": ("PWR", "URI"),
            "downstream_integrators": ("DHI", "LEN"),
        },
        ("cement", "aggregates", "infrastructure spending", "construction materials"),
        ("fiscal", "rates_down"),
    ),
    ThemeDefinition(
        "Water Infrastructure",
        "Infrastructure",
        "Water utilities, pumps, treatment and municipal infrastructure.",
        ("PHO", "FIW"),
        ("XYL", "WTS", "AWK", "AOS", "PNR"),
        {
            "upstream": ("NUE", "FCX"),
            "materials": ("NUE", "FCX"),
            "equipment": ("XYL", "WTS", "AOS", "PNR"),
            "manufacturers": ("XYL", "WTS", "AOS"),
            "infrastructure": ("AWK",),
            "downstream_integrators": ("PWR", "VMC"),
        },
        ("water", "treatment", "municipal", "utility capex", "water infrastructure"),
        ("defensive", "fiscal"),
    ),
    ThemeDefinition(
        "Agriculture",
        "Food & Agriculture",
        "Agricultural equipment, fertilizers, crops and food input cycle.",
        ("MOO",),
        ("DE", "ADM", "MOS", "CF", "BG", "CTVA"),
        {
            "upstream": ("CF", "MOS"),
            "materials": ("MOS", "CF"),
            "equipment": ("DE",),
            "manufacturers": ("DE", "CTVA"),
            "infrastructure": ("ADM", "BG"),
            "downstream_integrators": ("TSN", "GIS"),
        },
        ("agriculture", "fertilizer", "crop", "grain", "farm equipment"),
        ("inflation", "global_trade"),
    ),
    ThemeDefinition(
        "Food Supply",
        "Consumer Staples",
        "Food processors, grain handlers, packaged foods and protein supply chain.",
        ("XLP",),
        ("TSN", "GIS", "MDLZ", "CAG", "ADM", "SJM"),
        {
            "upstream": ("ADM", "BG"),
            "materials": ("ADM", "BG"),
            "equipment": ("DE",),
            "manufacturers": ("TSN", "GIS", "MDLZ", "CAG", "SJM"),
            "infrastructure": ("KEX", "CHRW"),
            "downstream_integrators": ("WMT", "KR", "COST"),
        },
        ("food supply", "grain", "protein", "packaged food", "consumer staples"),
        ("defensive", "inflation"),
    ),
    ThemeDefinition(
        "Logistics",
        "Transportation",
        "Parcel, freight brokerage, rail-adjacent transport and goods movement.",
        ("IYT",),
        ("UPS", "FDX", "XPO", "CHRW", "JBHT", "KEX"),
        {
            "upstream": ("XOM", "CVX"),
            "materials": ("NUE",),
            "equipment": ("KEX", "JBHT"),
            "manufacturers": ("UPS", "FDX", "XPO"),
            "infrastructure": ("KEX", "JBHT"),
            "downstream_integrators": ("AMZN", "WMT", "TGT"),
        },
        ("logistics", "freight", "parcel", "transport", "supply chain"),
        ("global_trade", "oil"),
    ),
    ThemeDefinition(
        "Aerospace",
        "Aerospace & Defense",
        "Commercial aerospace, engines, components and aviation cycle.",
        ("ITA", "XAR"),
        ("BA", "RTX", "GE", "LMT", "NOC", "TDG"),
        {
            "upstream": ("ATI", "NUE"),
            "materials": ("ATI", "NUE"),
            "equipment": ("RTX", "GE", "TDG"),
            "manufacturers": ("BA", "RTX", "GE"),
            "infrastructure": ("LMT", "NOC"),
            "downstream_integrators": ("DAL", "UAL", "AAL"),
        },
        ("aerospace", "engine", "aircraft", "aviation", "order book"),
        ("global_trade", "risk_on"),
    ),
    ThemeDefinition(
        "Cybersecurity",
        "Software",
        "Security software, identity, endpoint, cloud and zero-trust platforms.",
        ("HACK", "CIBR"),
        ("CRWD", "PANW", "FTNT", "ZS", "OKTA", "S"),
        {
            "upstream": ("MSFT", "AMZN"),
            "materials": tuple(),
            "equipment": ("PANW", "FTNT"),
            "manufacturers": ("CRWD", "ZS", "OKTA", "S"),
            "infrastructure": ("MSFT", "AMZN", "GOOGL"),
            "downstream_integrators": ("JPM", "UNH", "WMT"),
        },
        ("cybersecurity", "zero trust", "identity", "endpoint", "cloud security"),
        ("risk_on", "AI_capex"),
    ),
    ThemeDefinition(
        "Insurance",
        "Financial Services",
        "Property casualty, reinsurance, brokers and insurance pricing cycle.",
        ("KIE", "XLF"),
        ("BRK-B", "CB", "TRV", "AIG", "PGR", "MMC"),
        {
            "upstream": ("CME", "ICE"),
            "materials": tuple(),
            "equipment": ("MMC",),
            "manufacturers": ("CB", "TRV", "AIG", "PGR"),
            "infrastructure": ("BRK-B", "MMC"),
            "downstream_integrators": ("JPM", "BAC"),
        },
        ("insurance", "premium", "reinsurance", "catastrophe", "pricing"),
        ("risk_off", "rates"),
    ),
    ThemeDefinition(
        "Real Estate",
        "Real Assets",
        "REITs, towers, logistics warehouses, data center REITs and rate sensitivity.",
        ("XLRE", "VNQ"),
        ("PLD", "AMT", "EQIX", "WELL", "SPG", "O"),
        {
            "upstream": ("VMC", "MLM"),
            "materials": ("VMC", "MLM"),
            "equipment": ("ETN", "VRT"),
            "manufacturers": ("PLD", "AMT", "EQIX"),
            "infrastructure": ("WELL", "SPG", "O"),
            "downstream_integrators": ("AMZN", "MSFT", "T"),
        },
        ("REIT", "real estate", "cap rate", "data center REIT", "warehouse"),
        ("rates_down", "defensive"),
    ),
    ThemeDefinition(
        "Oil & Gas",
        "Energy",
        "Integrated oil, E&P, services and upstream energy capital discipline.",
        ("XLE", "OIH"),
        ("XOM", "CVX", "COP", "SLB", "EOG", "MPC"),
        {
            "upstream": ("EOG", "COP"),
            "materials": ("XOM", "CVX"),
            "equipment": ("SLB",),
            "manufacturers": ("XOM", "CVX", "MPC"),
            "infrastructure": ("KMI", "WMB"),
            "downstream_integrators": ("DAL", "UPS", "FDX"),
        },
        ("oil", "gas", "crude", "E&P", "energy services"),
        ("oil", "inflation"),
    ),
)


def get_theme_definitions() -> List[ThemeDefinition]:
    return list(THEME_UNIVERSE)


def find_theme_exposure(symbol: str, sector: str | None = None) -> List[ThemeDefinition]:
    normalized = symbol.strip().upper()
    sector_text = (sector or "").strip().lower()
    exposures: List[ThemeDefinition] = []
    for theme in THEME_UNIVERSE:
        mapped_symbols = set(theme.tickers)
        for bucket in theme.supply_chain.values():
            mapped_symbols.update(bucket)
        if normalized in mapped_symbols or (sector_text and sector_text in theme.category.lower()):
            exposures.append(theme)
    return exposures
